CREATE TABLE session_stage_settings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    game_session_id BIGINT NOT NULL REFERENCES game_sessions (id) ON DELETE CASCADE,
    stage_number INTEGER NOT NULL,
    duration_minutes INTEGER NOT NULL,
    interaction_mode VARCHAR(50) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_session_stage_number UNIQUE (game_session_id, stage_number)
);
