CREATE TABLE session_teams (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    game_session_id BIGINT NOT NULL REFERENCES game_sessions (id) ON DELETE CASCADE,
    name VARCHAR(150) NOT NULL,
    sort_order INTEGER NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_session_team_order UNIQUE (game_session_id, sort_order)
);

ALTER TABLE session_participants
    ADD COLUMN team_id BIGINT REFERENCES session_teams (id) ON DELETE SET NULL;
