package ru.vstu.medsim.kanban.domain;

public enum KanbanCardEventType {
    PRIORITY_SET,
    DEPARTMENT_ASSIGNED,
    EXECUTOR_ASSIGNED,
    WORK_STARTED,
    SOLUTION_SELECTED,
    SENT_TO_DEPARTMENT_REVIEW,
    DEPARTMENT_APPROVED,
    SOLUTION_FAILED,
    CHIEF_DOCTOR_APPROVED,
    RETURNED_TO_STAGE
}
